name: Build Deb Pack

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg-dev devscripts debhelper-compat dh-python python3-setuptools python3-all

      - name: Build Debian Package
        run: debuild --no-tgz-check -us -uc

      # This is moved to reflect the DIY/minimalist aims of the project
      # Remember to avoid leaking the token in the logs
      # what I mean is: don't enable verbose on curl
      - name: Generate MD5 and Release the Package
        run: bash .github/release.sh
        if: "github.repository == 'i3-workspace-names-daemon/i3-workspace-names-daemon'"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
