name: Build Deb Pack for development tests

on:
  push:
    branches:
        'deb-pack'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg-dev devscripts debhelper-compat dh-python python3-setuptools python3-all

      - name: Build Debian Package
        run: debuild --no-tgz-check -us -uc

      - name: Generate MD5 Checksum file
        run: |
          cd ${GITHUB_WORKSPACE}/..
          newest_deb=$(ls -t *.deb | head -n 1)
          md5sum "$newest_deb" > "${newest_deb%.deb}.md5"

      - name: Upload Package
        uses: actions/upload-artifact@v2
        with:
          name: i3-workspace-names-daemon
          path: |
            ${GITHUB_WORKSPACE}/../*.deb
            ${GITHUB_WORKSPACE}/../*.md5