name: Build Deb Pack

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      metadata: read
      packages: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg-dev devscripts debhelper-compat dh-python python3-setuptools python3-all

      - name: Build Debian Package
        run: debuild --no-tgz-check -us -uc

      - name: Generate MD5 and Release the Package
        run: bash .github/release.sh
        env:
          - GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # this is moved to avoid leaking the token in the logs
